Textbook.create([
  { id: 1, name: "音トレ道場6段", series: "音トレ", level: "英検準1級", cover_image: "ontra06_top_2.png" },
  { id: 2, name: "音トレ道場5段", series: "音トレ", level: "英検2級", cover_image: "ontra05_top.png" },
  { id: 3, name: "音トレ道場4段", series: "音トレ", level: "英検準2級", cover_image: "ontra04_top.png" },
  { id: 4, name: "音トレ道場3段", series: "音トレ", level: "英検3級", cover_image: "ontra03_top.png" },
  { id: 5, name: "音トレ道場2段", series: "音トレ", level: "英検4級", cover_image: "ontra02_top.png" },
  { id: 6, name: "音トレ道場初段", series: "音トレ", level: "英検5級", cover_image: "ontra01_top.png" },
  { id: 7, name: "リズムでマスター英検準1級", series: "リズムでマスター", level: "英検準1級", cover_image: "rhythmas_06.png" },
  { id: 8, name: "リズムでマスター英検2級", series: "リズムでマスター", level: "英検2級", cover_image: "rhythmas_05.png" },
  { id: 9, name: "リズムでマスター英検準2級", series: "リズムでマスター", level: "英検準2級", cover_image: "rhythmas_04.png" },
  { id: 10, name: "リズムでマスター英検3級", series: "リズムでマスター", level: "英検3級", cover_image: "rhythmas_03.png" },
  { id: 11, name: "リズムでマスター英検4級", series: "リズムでマスター", level: "英検4級", cover_image: "rhythmas_02.png" },
  { id: 12, name: "リズムでマスター英検5級", series: "リズムでマスター", level: "英検5級", cover_image: "rhythmas_01.png" }
])

Listening.create([
  { id: 1, title: "アンジェラ・リー・ダックワース 「成功のカギは、やり抜く力」", level: "英検1級", duration: "6:12", video: "https://youtu.be/H14bBuluwB8?si=hV4tJM9rYqsSRD-Y" },
  { id: 2, title: "ケリー・マクゴニガル: 「ストレスと友達になる方法」", level: "英検1級", duration: "14:28", video: "https://youtu.be/RcGyVTAoXEU?si=xnZFv7JtMlk6gxHA" },
  { id: 3, title: "Kang Lee: Can you really tell if a kid is lying?", level: "英検1級", duration: "13:37", video: "https://youtu.be/6diqpGKOvic?si=vow8_t5Jc5gNnkAZ" },
  { id: 4, title: "セレステ・ヘッドリー: 「上手に会話する10の方法」", level: "英検1級", duration: "12:06", video: "https://youtu.be/H6n3iNh4XLI?si=IIEihiQfTAIRcDO7" },
  { id: 5, title: "ジョシュ・カウフマン: 「最初の20時間 — あらゆることをサクッと学ぶ方法」", level: "英検1級", duration: "19:27", video: "https://youtu.be/5MgBikgcWnY?si=ODNcRF02FMAZkLG-" },
  { id: 6, title: "Jiggy's Japanglish Podcast: Ichiro, Ohtani & Osakaー世界で戦う日本人に英語は必要？", level: "英検2級", duration: "19:27", video: "https://youtu.be/0t_tpsVgn0o?si=y4sBoF6W-nIb5M5R" },
  { id: 7, title: "Jiggy's Japanglish Podcast: Tattoos in Japanー日本でタトゥーってアリ？ナシ？", level: "英検準1級", duration: "19:27", video: "https://youtu.be/TCeYXPkCoZQ?si=0yTORNi7_TasU8Sa" },
  { id: 8, title: "Atsueigo: 【英語上手すぎ】日本生まれ育ちでペラペラのChinatsuさんと英語で対談してみた", level: "英検準1級", duration: "33:05", video: "https://youtu.be/Rvo9xt32Rtc?si=FL5m6Co9u_KrVmrP" },
  { id: 9, title: "だいじろー: アメリカ英語発音入門 完全ガイド", level: "英語の発音", duration: "65:00", video: "https://youtu.be/nEpewJsEgUg?si=d-mTAEnJKt40uDw6" },
  { id: 10, title: "Atsueigo: 【永久保存版】たった30分で発音記号を完全攻略【速習まとめ】", level: "英語の発音", duration: "31:07", video: "https://youtu.be/Qe3EmiFWgGM?si=VOOWkI39o4eTO_6w" },
  { id: 11, title: "English with Venya: Ep.27 - Tipping Culture in America", level: "英検準1級", duration: "5:41", video: "https://youtu.be/cLvQw40iTVg?si=cjNq1xsO_lb24W2c" },
  { id: 12, title: "English with Venya: Ep.26 - American College/University Life", level: "英検準1級", duration: "6:51", video: "https://youtu.be/NAY3Zw79r1A?si=s4XIdJ6QMcrkuKrv" },
  { id: 13, title: "English with Venya: Ep.25 - Small Talk LIKE A PRO!", level: "英検準1級", duration: "5:55", video: "https://youtu.be/0AIMST7C3JE?si=mdjFjO9gesHTieXD" },
])


textbook = Textbook.find_by(name: "音トレ道場6段")
Chapter.create([
  {textbook: textbook, series: "長文", title: "TOPIC1 History 歴史"},
  {textbook: textbook, series: "長文", title: "TOPIC2 Society 社会"},
  {textbook: textbook, series: "長文", title: "TOPIC3 Economy 経済"},
  {textbook: textbook, series: "長文", title: "TOPIC4 Science 科学"},
  {textbook: textbook, series: "長文", title: "TOPIC5 Technology 技術"},
  {textbook: textbook, series: "長文", title: "TOPIC6 Environmental Issues 環境問題"},
  {textbook: textbook, series: "長文", title: "TOPIC7 Crimes and Judicial System 犯罪と司法システム"},
  {textbook: textbook, series: "長文", title: "TOPIC8 Health and Medicine 健康・医療"},
  {textbook: textbook, series: "長文", title: "TOPIC9 Psychology 心理学"},
  {textbook: textbook, series: "長文", title: "TOPIC10 Politics 政治"},
  {textbook: textbook, series: "長文", title: "TOPIC11 Education 教育"},
  {textbook: textbook, series: "長文", title: "TOPIC12 Entertainment and Leisure 娯楽・レジャー"},
  {textbook: textbook, series: "長文", title: "TOPIC13 Diet and Nutrition 食事と栄養学"},
  {textbook: textbook, series: "長文", title: "TOPIC14 Industry 産業"},
  {textbook: textbook, series: "長文", title: "TOPIC15 Agriculture 農業"},
  {textbook: textbook, series: "長文", title: "TOPIC16 Customs 慣習・制度"},
  {textbook: textbook, series: "長文", title: "TOPIC17 Business ビジネス"},
  {textbook: textbook, series: "長文", title: "TOPIC18 Law 法律"},
  {textbook: textbook, series: "長文", title: "TOPIC19 International Relations 国際関係"},
  {textbook: textbook, series: "長文", title: "TOPIC20 Biology 生物"},
  {textbook: textbook, series: "リスニング", title: "SCENE1 Daily Life 日常の様々な場面での対話・連絡"},
  {textbook: textbook, series: "リスニング", title: "SCENE2 College/ Graduate School キャンパスでの対話・案内"},
  {textbook: textbook, series: "リスニング", title: "SCENE3 Business Scenes ビジネスでの対話・連絡"},
  {textbook: textbook, series: "リスニング", title: "SCENE4 Announcements/ Sales Talk アナウンス・セールストーク"},
  {textbook: textbook, series: "リスニング", title: "SCENE5 Lectures 講義"},
])

textbook = Textbook.find_by(name: "音トレ道場5段")
Chapter.create([
  {textbook: textbook, series: "長文", title: "TOPIC1 Education 教育"},
  {textbook: textbook, series: "長文", title: "TOPIC2 Astronomy 天文学"},
  {textbook: textbook, series: "長文", title: "TOPIC3 Culture① 文化①"},
  {textbook: textbook, series: "長文", title: "TOPIC4 Environment 環境"},
  {textbook: textbook, series: "長文", title: "TOPIC5 Travel & Transportation 旅行・交通"},
  {textbook: textbook, series: "長文", title: "TOPIC6 Daily Life① 日常生活①（メール）"},
  {textbook: textbook, series: "長文", title: "TOPIC7 Health & Medicine① 健康・医療①"},
  {textbook: textbook, series: "長文", title: "TOPIC8 Resources and Energy 資源・エネルギー"},
  {textbook: textbook, series: "長文", title: "TOPIC9 Natural Science 自然科学"},
  {textbook: textbook, series: "長文", title: "TOPIC10 History 歴史"},
  {textbook: textbook, series: "長文", title: "TOPIC11 Daily Life② 日常生活①（メール）"},
  {textbook: textbook, series: "長文", title: "TOPIC12 Health & Medicine② 健康・医療②"},
  {textbook: textbook, series: "長文", title: "TOPIC13 Technology 科学技術"},
  {textbook: textbook, series: "長文", title: "TOPIC14 Space 天文・宇宙"},
  {textbook: textbook, series: "長文", title: "TOPIC15 Ecology 生態系"},
  {textbook: textbook, series: "長文", title: "TOPIC16 Daily Life③ 日常生活③（手紙）"},
  {textbook: textbook, series: "長文", title: "TOPIC17 Health & Medicine③ 健康・医療③"},
  {textbook: textbook, series: "長文", title: "TOPIC18 Culture② 文化②"},
  {textbook: textbook, series: "長文", title: "TOPIC19 Society 社会"},
  {textbook: textbook, series: "長文", title: "TOPIC20 Culture③ 文化③"},
  {textbook: textbook, series: "リスニング", title: "Scene1 Situation Dialogues 様々な場面での対話"},
  {textbook: textbook, series: "リスニング", title: "Scene2 Story Narrations 様々なストーリーのナレーション"},
  {textbook: textbook, series: "リスニング", title: "Scene3 Speeches and Announcements 様々なスピーチ・お知らせ"},
  {textbook: textbook, series: "リスニング", title: "Scene4 Topic Narrations 様々な説明文"},
  {textbook: textbook, series: "リスニング", title: "Scene5 Listening Comprehension Mock Test リスニング・ミニ模試"},
])

textbook = Textbook.find_by(name: "音トレ道場4段")
Chapter.create([
  {textbook: textbook, series: "長文", title: "TOPIC1 Daily Life 日常生活"},
  {textbook: textbook, series: "長文", title: "TOPIC2 Business ビジネス"},
  {textbook: textbook, series: "長文", title: "TOPIC3 Travel & Transportation 旅行・交通"},
  {textbook: textbook, series: "長文", title: "TOPIC4 Entertainment and Leisure 娯楽・レジャー"},
  {textbook: textbook, series: "長文", title: "TOPIC5 Health & Medicine5 健康・医療"},
  {textbook: textbook, series: "長文", title: "TOPIC6 Technology 科学技術"},
  {textbook: textbook, series: "長文", title: "TOPIC7 Natural Science 自然科学"},
  {textbook: textbook, series: "長文", title: "TOPIC8 Politics 政治"},
  {textbook: textbook, series: "長文", title: "TOPIC9 Environment 環境"},
  {textbook: textbook, series: "長文", title: "TOPIC10 Education 教育"},
  {textbook: textbook, series: "長文", title: "TOPIC11 Culture 文化"},
  {textbook: textbook, series: "長文", title: "TOPIC12 Society 社会"},
  {textbook: textbook, series: "長文", title: "TOPIC13 Biology 伝記"},
  {textbook: textbook, series: "長文", title: "TOPIC14 History 歴史"},
  {textbook: textbook, series: "長文", title: "TOPIC15 International Affairs 国際情勢"},
  {textbook: textbook, series: "リスニング", title: "Scene1 Restaurant・Dining レストラン・食事"},
  {textbook: textbook, series: "リスニング", title: "Scene2 Shopping 買い物"},
  {textbook: textbook, series: "リスニング", title: "Scene3 Telephone Conversation 電話での会話"},
  {textbook: textbook, series: "リスニング", title: "Scene4 School Life 学校生活"},
  {textbook: textbook, series: "リスニング", title: "Scene5 Traveling & Leisure 旅行・レジャー"},
  {textbook: textbook, series: "リスニング", title: "Scene6 Offer & Request 誘い・依頼"},
  {textbook: textbook, series: "リスニング", title: "Scene7 Daily Expressions① 日常生活① 様々な表現"},
  {textbook: textbook, series: "リスニング", title: "Scene8 Daily Expressions② 日常生活② 類似表現・反対表現"},
  {textbook: textbook, series: "リスニング", title: "Scene9 Narration① 様々なナレーション①"},
  {textbook: textbook, series: "リスニング", title: "Scene10 Narration② 様々なナレーション②"},
])
